[versions]
minSdk = "26"
compileSdk = "36"
targetSdk = "36"
versionCode = "1"
versionName = "1.0.0"

kotlin = "2.2.21"
androidGradlePlugin = "8.13.1"
ksp = "2.3.2"
ktorfit = "2.6.5"
mokoResources = "0.25.2"
moduleGraph = "1.3.3"
detekt = "1.23.8"
dateTime = "0.6.2"
coroutines = "1.10.2"
decompose = "3.4.0"
ktor = "3.3.3"
replica = "1.5.2-alpha"
koin = "4.1.1"
kermit = "2.0.8"
activity = "1.12.0"
coil = "3.3.0"
splashscreen = "1.2.0"
chucker = "4.2.0"
hyperion = "0.9.38"
hyperionAddons = "0.3.3"
composeRules = "0.4.28"
composeMultiplatform = "1.9.3"
materialIcons = "1.7.3"
form = "1.2.0"
securityCrypto = "1.1.0-alpha06"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTime" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }

replica-core = { module = "com.github.aartikov:replica-core", version.ref = "replica" }
replica-algebra = { module = "com.github.aartikov:replica-algebra", version.ref = "replica" }
replica-android-network = { module = "com.github.aartikov:replica-android-network", version.ref = "replica" }
replica-decompose = { module = "com.github.aartikov:replica-decompose", version.ref = "replica" }
replica-devtools = { module = "com.github.aartikov:replica-devtools", version.ref = "replica" }

form-validation = { module = "ru.mobileup:kmm-form-validation", version.ref = "form" }

koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
logger-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Used in build-logic/DetektPlugin
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { module = "io.nlopez.compose.rules:detekt", version.ref = "composeRules" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIcons" }

security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCrypto" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

moko-resources = { module = "dev.icerock.moko:resources", version.ref = "mokoResources" }
moko-resourcesCompose = { module = "dev.icerock.moko:resources-compose", version.ref = "mokoResources" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
hyperion-core = { module = "com.willowtreeapps.hyperion:hyperion-core", version.ref = "hyperion" }
hyperion-recorder = { module = "com.willowtreeapps.hyperion:hyperion-recorder", version.ref = "hyperion" }
hyperion-crash = { module = "com.willowtreeapps.hyperion:hyperion-crash", version.ref = "hyperion" }
hyperion-disk = { module = "com.willowtreeapps.hyperion:hyperion-disk", version.ref = "hyperion" }
hyperion-addons-logs = { module = "me.nemiron.hyperion:logs", version.ref = "hyperionAddons" }
hyperion-addons-networkEmulation = { module = "me.nemiron.hyperion:network-emulation", version.ref = "hyperionAddons" }
hyperion-addons-chucker = { module = "me.nemiron.hyperion:chucker", version.ref = "hyperionAddons" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

[bundles]
decompose = ["decompose-core", "decompose-compose"]
replica = ["replica-core", "replica-algebra", "replica-android-network", "replica-decompose"]
ktor = [
    "ktor-core",
    "ktor-auth",
    "ktor-serialization",
    "ktor-content-negotiation",
    "ktor-logging",
    "ktor-android"
]
hyperion = [
    "hyperion-core",
    "hyperion-recorder",
    "hyperion-crash",
    "hyperion-disk",
    "hyperion-addons-logs",
    "hyperion-addons-networkEmulation",
    "hyperion-addons-chucker"
]
coil = [
    "coil",
    "coil-okhttp"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
module-graph = { id = "ru.mobileup.module-graph", version.ref = "moduleGraph" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "mokoResources" }
custom-detekt = { id = "custom.detekt" }
custom-lint = { id = "custom.lint" }
